name: Publish Docker Image

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'

jobs:
  publish:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ebrakke --password-stdin

      - name: Build and push
        run: |
          TAG_SHA="ghcr.io/ebrakke/group-chat:${{ github.sha }}"
          TAG_LATEST="ghcr.io/ebrakke/group-chat:latest"
          docker build -f Dockerfile.once -t "$TAG_SHA" -t "$TAG_LATEST" .
          docker push "$TAG_SHA"
          docker push "$TAG_LATEST"
